robot:
  name: ur10esrh
  manipulators:
    right_manipulator:
      side: right
      arm:
        name: ur10e
        main_group: manipulator
        moveit_path:
          package: sr_multi_moveit_config
          relative_path: /config/ur
        extra_groups_config_path: /config
        group_states:
          - home
          - up
