gazebo_ros_control:
    pid_gains:
      ra_shoulder_pan_joint:  {p: 500, i: 1000, d: 0.1, i_clamp_max: 1000, i_clamp_min: -1000, antiwindup: true}
      ra_shoulder_lift_joint: {p: 500, i: 1000, d: 0.1, i_clamp_max: 1000, i_clamp_min: -1000, antiwindup: true}
      ra_elbow_joint:         {p: 500, i: 1000, d: 0.1, i_clamp_max: 1000, i_clamp_min: -1000, antiwindup: true}
      ra_wrist_1_joint:       {p: 500, i: 1000, d: 0.1, i_clamp_max: 1000, i_clamp_min: -1000, antiwindup: true}
      ra_wrist_2_joint:       {p: 500, i: 1000, d: 0.1, i_clamp_max: 1000, i_clamp_min: -1000, antiwindup: true}
      ra_wrist_3_joint:       {p: 500, i: 1000, d: 0.1, i_clamp_max: 1000, i_clamp_min: -1000, antiwindup: true}


ra_trajectory_controller:
  type: "velocity_controllers/ComplianceController"
  joints:
    - ra_shoulder_pan_joint
    - ra_shoulder_lift_joint
    - ra_elbow_joint
    - ra_wrist_1_joint
    - ra_wrist_2_joint
    - ra_wrist_3_joint
  compliance_command_timeout: 1.5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 1.0
      ra_shoulder_pan_joint: {trajectory: 0.3, goal: 0.1}
      ra_shoulder_lift_joint: {trajectory: 0.3, goal: 0.1}
      ra_elbow_joint: {trajectory: 0.3, goal: 0.1}
      ra_wrist_1_joint: {trajectory: 0.3, goal: 0.1}
      ra_wrist_2_joint: {trajectory: 0.3, goal: 0.1}
      ra_wrist_3_joint: {trajectory: 0.3, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  allow_partial_joints_goal: true
  #!!These values have not been optimized!!
  gains:
    ra_shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    ra_shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    ra_elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    ra_wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    ra_wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    ra_wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}

  # Use a feedforward term to reduce the size of PID gains
  velocity_ff:
    ra_shoulder_pan_joint: 1.0
    ra_shoulder_lift_joint: 1.0
    ra_elbow_joint: 1.0
    ra_wrist_1_joint: 1.0
    ra_wrist_2_joint: 1.0
    ra_wrist_3_joint: 1.0
