robot:
  name: ursrh
  manipulators:
    right_manipulator:
      side: right
      arm:
        name: ur10e
        main_group: manipulator
        moveit_path:
          package: sr_multi_moveit_config
          relative_path: /config/ur
        extra_groups_config_path: /config
        group_states:
          - home
          - up
      hand: True
    left_manipulator:
      side: left
      arm:
        name: ur10e
        main_group: manipulator
        other_groups:
          - endeffector
        moveit_path:
          package: sr_multi_moveit_config
          relative_path: /config/ur
        extra_groups_config_path: /config
        group_states:
          - home
          - up
      hand: False

ra_sr_ur_robot_hw:
  # Hand E payload
  payload_mass_kg: 4.55

  # Hand E payload centre of inertia (estimated, need exact from Hardware)
  payload_center_of_mass_m: [0.0, 0.0, 0.12]

la_sr_ur_robot_hw:
  # No hand
  payload_mass_kg: 0.0
