la_sr_ur_robot_hw:
  type: sr_ur_robot_hw/UrArmRobotHW
  
  # ra for right side arm la for left side arm
  robot_id: la
  
  # for sending robot programs
  robot_ip_address: 192.168.1.1
  
  # for the server that moves the robot 
  control_pc_ip_address: 192.168.1.100

  # UR10 speed scale (0.0-1.0)
  speed_scale: 0.5
  