rw_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - rh_WRJ1
    - rh_WRJ2
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 10.0
      rh_WRJ1: {trajectory: 2.0, goal: 2.1}
      rh_WRJ2: {trajectory: 2.0, goal: 2.1}
  stop_trajectory_duration: 0.5
  allow_partial_joints_goal: true
