arm_and_wrist:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0
  dpos: 0.001
  drot: 0.01
  mode: gd_c

arm_and_manipulator:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0
  dpos: 0.001
  drot: 0.01
  mode: gd_c

two_arms:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0
  dpos: 0.001
  drot: 0.01
  mode: gd_c

two_arms_and_wrists:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0
  dpos: 0.001
  drot: 0.01
  mode: gd_c